name: glib
description: Miscellaneous GLib utilities for Dart and Flutter.
homepage: https://github.com/ubuntu-flutter-community/glib.dart
repository: https://github.com/ubuntu-flutter-community/glib.dart
issue_tracker: https://github.com/ubuntu-flutter-community/glib.dart/issues
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  ffi: ^2.0.1
  meta: ^1.8.0

dev_dependencies:
  ffigen: 7.1.0
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.22.2
