enum GUserDirectory {
  G_USER_DIRECTORY_DESKTOP,
  G_USER_DIRECTORY_DOCUMENTS,
  G_USER_DIRECTORY_DOWNLOAD,
  G_USER_DIRECTORY_MUSIC,
  G_USER_DIRECTORY_PICTURES,
  G_USER_DIRECTORY_PUBLIC_SHARE,
  G_USER_DIRECTORY_TEMPLATES,
  G_USER_DIRECTORY_VIDEOS
}

const G_USER_DIRECTORY_DESKTOP = GUserDirectory.G_USER_DIRECTORY_DESKTOP;
const G_USER_DIRECTORY_DOCUMENTS = GUserDirectory.G_USER_DIRECTORY_DOCUMENTS;
const G_USER_DIRECTORY_DOWNLOAD = GUserDirectory.G_USER_DIRECTORY_DOWNLOAD;
const G_USER_DIRECTORY_MUSIC = GUserDirectory.G_USER_DIRECTORY_MUSIC;
const G_USER_DIRECTORY_PICTURES = GUserDirectory.G_USER_DIRECTORY_PICTURES;
const G_USER_DIRECTORY_PUBLIC_SHARE =
    GUserDirectory.G_USER_DIRECTORY_PUBLIC_SHARE;
const G_USER_DIRECTORY_TEMPLATES = GUserDirectory.G_USER_DIRECTORY_TEMPLATES;
const G_USER_DIRECTORY_VIDEOS = GUserDirectory.G_USER_DIRECTORY_VIDEOS;

enum GFormatSizeFlags {
  G_FORMAT_SIZE_DEFAULT(0),
  G_FORMAT_SIZE_LONG_FORMAT(1 << 0),
  G_FORMAT_SIZE_IEC_UNITS(1 << 1),
  G_FORMAT_SIZE_BITS(1 << 2);

  const GFormatSizeFlags(this.value);
  final int value;
}

const G_FORMAT_SIZE_DEFAULT = GFormatSizeFlags.G_FORMAT_SIZE_DEFAULT;
const G_FORMAT_SIZE_LONG_FORMAT = GFormatSizeFlags.G_FORMAT_SIZE_LONG_FORMAT;
const G_FORMAT_SIZE_IEC_UNITS = GFormatSizeFlags.G_FORMAT_SIZE_IEC_UNITS;
const G_FORMAT_SIZE_BITS = GFormatSizeFlags.G_FORMAT_SIZE_BITS;
